esphome:
  includes:
    - LivoloReadRF433.h

  name: "livoloreadrf433"
  friendly_name: LivoloReadRF433

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "key"

ota:
  password: "password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Livoloreadrf433"
    password: "password"

captive_portal:

sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new LivoloReadRF433();
    App.register_component(my_sensor);
    return {my_sensor->RemoteID ,my_sensor->KeyCode};

  sensors:
    - name: "RemoteID"
      force_update: true
    - name: "KeyCode"    
      force_update: true
