esphome:
  includes:
    - LivoloReadRF433.h

  name: "livoloreadrf433"
  friendly_name: LivoloReadRF433

# We return the support of custom components.
external_components:
   - source:
       type: git
       url: https://github.com/esphome/esphome
       ref: 2024.12.4
     components: [ custom, custom_component ]

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "key"

ota:
  password: "password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Livoloreadrf433"
    password: "password"

captive_portal:

sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new LivoloReadRF433();
    App.register_component(my_sensor);
    return {my_sensor->RemoteID ,my_sensor->KeyCode};

  sensors:
    - name: "RemoteID"
      force_update: true
# Обнуляем показания сенсора через 0.5 секунды после отпускания кнопки 
# We reset the sensor readings 0.5 seconds after the release of the button
      filters:   
       - timeout:
           timeout: 0.5s
           value: !lambda return 0;

    - name: "KeyCode"    
      force_update: true
# Обнуляем показания сенсора через 0.5 секунды после отпускания кнопки 
# We reset the sensor readings 0.5 seconds after the release of the button
      filters:   
       - timeout:
           timeout: 0.5s
           value: !lambda return 0;
